// Code generated by "genpal -type=User,GroupChat -output=testdata/privacy.go"

package main

import (
	"cloud.google.com/go/firestore"
	pal "github.com/privacy-pal/privacy-pal/pkg"
)

func (u *User) HandleAccess(dataSubjectId string, currentDocumentID string) map[string]interface{} {
	return nil
}

func (u *User) HandleDeletion(dataSubjectId string) (nodesToTraverse []pal.Locator, deleteNode bool, fieldsToUpdate []firestore.Update) {
	return nil, false, nil
}
func (g *GroupChat) HandleAccess(dataSubjectId string, currentDocumentID string) map[string]interface{} {
	return nil
}

func (g *GroupChat) HandleDeletion(dataSubjectId string) (nodesToTraverse []pal.Locator, deleteNode bool, fieldsToUpdate []firestore.Update) {
	return nil, false, nil
}
